[platformio]
default_envs = mqtt

[common]
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

[env:mqtt]
platform = espressif32
board = esp32dev
board_build.partitions = default_8MB.csv
src_filter = +<src/incubator_esp32_mqtt>
lib_deps =
    tzapu/WiFiManager @ 2.0.16-beta
    knolleary/PubSubClient @ 2.8
    adafruit/Adafruit AHTX0 @ 2.0.5
    marcoschwartz/LiquidCrystal_I2C @ 1.1.4
    adafruit/Adafruit SSD1306 @ 2.5.13
    adafruit/Adafruit GFX Library @ 1.11.11
    bblanchon/ArduinoJson @ 6.21.3
    r-downing/AutoPID @ 1.0.2

[env:ap]
platform = espressif32
board = esp32dev
board_build.partitions = default_8MB.csv
src_filter = +<src/inkubatorAP>
lib_deps =
    knolleary/PubSubClient @ 2.8
    links2004/WebSockets @ 2.4.1
    adafruit/DHT sensor library @ 1.4.6
    bblanchon/ArduinoJson @ 6.21.3
    makuna/Rtc @ 2.4.0
    adafruit/Adafruit Unified Sensor @ 1.1.14
